### PR TITLE
Add *script support and diagnostics

### PR DESCRIPTION
**Pull request by CareyJWilliams**
With the introduction of #33, the extension no longer supports *script calls due to its security model.
This hopefully doesn't affect too many people, but for those it does I've tried to address that in this PR.

Here we:

- Add a new allowUnsafeScript setting to enable script usage in games
- Add permanent diagnostics for *script usage, either warning if the setting above is enabled or an error if it's disabled

Need to add tests and maybe tidy a few things, but thought I'd solicit some feedback before going any further.
Always-on diagnostics might sound like a bold choice, but I think it's the right call with *script. Especially now we're using VS Code webviews, the risk of any malicious ChoiceScript code (a funny thought but very possible scenario) is much higher.

**Setting**

Screenshot 2024-11-02 at 17 55 19

**Diagnostics: Error**

Screenshot 2024-11-02 at 17 55 24

**Diagnostics: Warn**

Screenshot 2024-11-02 at 17 55 14

### CODE REVIEW

**Comment by CareyJWilliams** [comment]
> Oh, hey, this is a great catch.
> 
> My first thought was "let trusted workspaces handle this" but I suspect folks will use `*script` by cutting and pasting code into their game. Given that, I like the approach of having an always-on warning.
> 
> I wonder if we should add the ability to turn the warning/error off with a comment above the `*script` command, the way that eslint lets you disable a rule for a given line. If so, we'd do well to add a quick fix on the warning/error to disable it by inserting the appropriate `*comment` line above it.

This is a nice idea but it's a big backdoor - what happens if the random code you're copying and pasting has that comment above it?

At that point it might be better to just have three settings:
- on with warning 
- off with error (default imo)
- on with no warning (YOLO)

WDYT?

**Comment by sgranade** [comment]
I don't think being able to turn off the warnings or errors are any more of a backdoor than having them always on. We don't refuse to run a game because it has errors or warnings, and if I were going to spread malicious code, I'd say "ignore the error in VS Code." Anyone suggesting legitimate examples would do the same.

I suppose if we wanted to put teeth behind it, we'd have the extension refuse to run a game if there's an unallowed `*script` command. (We could have the extension refuse to run a game with errors overall, though I'd suggest we have that discussion separately.)

For me, it comes down to what security posture we want to take:
* Global error or warn always so the author's attention is drawn to it; game still runs.
  * Downside: warning fatigue where the author just ignores the error or warning
* Global error or warn always; game only runs if it's a warning.
  * Downside: global setting does nothing to help if new `*script` commands are added after downgrading to a warning.
* Global error or warn always; ability to disable on an individual line; game still runs.
  * Downside: people may cut and paste code with the disabling comment; potential warning fatigue
* Global error or warn always; ability to disable on an individual line; game only runs if it's a warning.
  * Downside: people may cut and paste code with the disabling comment

(The global error/warn/none has, to my mind, the same downsides as global error/warn: if you disable the error/warning, you won't get any protection, tissue-thin as it may be, if you add `*script` commands.)

I'm open to other suggestions, though. We could, for example, do a modal warning or notification on adding a `*script` command to a file as a more active notice.

**Comment by CareyJWilliams** [comment]
> I don't think being able to turn off the warnings or errors are any more of a backdoor than having them always on. We don't refuse to run a game because it has errors or warnings, and if I were going to spread malicious code, I'd say "ignore the error in VS Code." Anyone suggesting legitimate examples would do the same.

My point was more that I don't see the value in the individual comment silencing method _versus_ just allowing global disable of warnings. The former is harder to implement, more work for the end user that does wish to disable warnings and (in my humble opinion) is not any more secure than a YOLO "turn off" for the reasons you state above (if someone wanted to do something malicious they'll just use the disable comments anyway). I don't foresee a scenario where someone wants to comment out _some_ *script commands but not others, and I also suspect it's not used commonly enough that people will be copying and pasting new *script commands in daily. Thus, I'd be erring more towards trying to keep it always obvious when you're in an insecure state without falling into "warning fatigue".

Moving forwards with that line of thinking you could allow error/warning disables and use a warning icon in a game run, or even a warning banner in the game itself, both demonstrated below:
Screenshot 2024-11-07 at 00 39 56

I think a notification or modal on any copy + paste would feel quite knee-jerky, but we could do a notification on run:

Screenshot 2024-11-07 at 00 51 36

There's still a risk of fatigue and it being ignored eventually, but I also think we have to accept there's only so much that we can do before the responsibility is the end-user's?

**Comment by sgranade** [comment]
Having mulled over this more today, I think we should go with a general option to warn or not-warn (skip error) globally, and leave the rest to the authors to manage.

**Comment by CareyJWilliams** [comment]
> Having mulled over this more today, I think we should go with a general option to warn or not-warn (skip error) globally, and leave the rest to the authors to manage.

I've made `allowUnsafeScript` setting an enumeration of three options:
- Never: won't run *script and will mark them as errors
- Warn: will run *script commands but will mark them with warnings
- Allow: will run *script commands and won't validate/mark them

I've also added unit tests and caught the ugly *script error in cs-extension.js to turn it into something more helpful to the end user.

**Pull request merged**
